### ISSUE TITLE
Dialyzer error when you got `URL.Parser.ParseError`

### ISSUE THREAD

**Issue by shahryarjb** [kipcole9/url#5]
Hi, For example you put this `"geo:48.198634,--16.371648,3.4;crs=wgs84;u=40.0"` to force the function shows you an error

### You will get this:

```elixir
iex(3)> URL.new("geo:48.198634,--16.371648,3.4;crs=wgs84;u=40.0")
{:ok,
 %URL{
   scheme: "geo",
   path: "48.198634,--16.371648,3.4;crs=wgs84;u=40.0",
   query: nil,
   fragment: nil,
   authority: nil,
   userinfo: nil,
   host: nil,
   port: nil,
   parsed_path: {:error,
    {URL.Parser.ParseError,
     "expected an string of digits while processing ASCII character equal to \"-\" or equal to \"+\" or nothing, followed by an string of digits, followed by a dot character, followed by an string of digits or ASCII character equal to \"-\" or equal to \"+\" or nothing, followed by an string of digits. Detected on line 1 at \"-16.371648,3.4;crs=w\" <> ..."}}
 }}
```

But there is no type for `URL.Parser.ParserError`

https://github.com/kipcole9/url/blob/master/lib/url.ex#L12

I think if it returns something like `{:error, reason}`, can be more useful.
Thank you in advance

**Comment by kipcole9** [comment]
I have pushed [a commit](https://github.com/kipcole9/url/commit/4ac8c4a74810b6b636ca1f62b9894d2cb5b4f27a) that addresses this issue but in a slightly different way.

The function `URL.new/1` now always returns a tuple - in both the error case and the no error case. The return type is `{:ok, URL.t()} | {:error, {module(), String.t()}}`.

The previous approach resulted in path parse errors being embedded in the `t:URL.t/0` struct which is very unpleasant and confusing.

This also means that negative tests (for error cases) are simpler to write. I need to add error tests for completeness so I'm not closing the issue yet.

If you have a chance to try this version, running from GitHub with `{:url, GitHub: "kipcole9/url"}` and report any other issues that would be great.

Since this is a breaking change I have bumped the version to `2.0.0`.

**Comment by shahryarjb** [comment]
Hello sir @kipcole9 I will test and update this issue if you give me 4 days. Thank you

**Comment by shahryarjb** [comment]
Hi sir, @kipcole9 
Thank you for all you efforts.

I got some warnings of unused vars in my console

```
warning: variable "territory" is unused (if the variable is not meant to be used, prefix it with an underscore)
  lib/url/tel.ex:74: URL.Tel.parse_phone_number/2

warning: variable "format" is unused (if the variable is not meant to be used, prefix it with an underscore)
  lib/url/tel.ex:78: URL.Tel.format/2

warning: function cldr_territory/0 is unused
  lib/url/tel.ex:96: URL.Tel (module)

warning: function get_territory/0 is unused
  lib/url/tel.ex:87: URL.Tel (module)

warning: function gettext_territory/0 is unused
  lib/url/tel.ex:109: URL.Tel (module)

warning: function parse_phone_number/2 is unused
  lib/url/tel.ex:74: URL.Tel (module)

warning: function phone_context/1 is unused
  lib/url/tel.ex:82: URL.Tel (module)
```

Thank you

**Comment by kipcole9** [comment]
Thanks for the report.  These warnings arise when `ex_phone_number` and `ex_cldr` aren't configured. I have pushed a commit that removes the warnings in these cases.  Thanks for your patience.

May I ask you to try from GitHub one more time?

**Comment by shahryarjb** [comment]
Thank you sir, I retested it and I have no warnings from `ex_url`, the only exists warning is
```
warning: the log level :warn is deprecated, use :warning instead
  (logger 1.15.1) lib/logger.ex:1137: Logger.elixir_level_to_erlang_level/1
  (logger 1.15.1) lib/logger.ex:618: anonymous fn/2 in Logger.configure/1
  (elixir 1.15.1) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
  (logger 1.15.1) lib/logger.ex:616: Logger.configure/1
  lib/ex_phone_number/metadata/phone_metadata.ex:73: (module)
  (elixir 1.15.1) src/elixir_compiler.erl:66: :elixir_compiler.dispatch/4

Generated ex_phone_number app
```
which is not fro your library.

If I find another issue I create a new one.

Again Thank you for all your efforts.

**Comment by kipcole9** [comment]
Thanks for the confirmation and the collaboration. I will publish an update to hex now.

**Comment by kipcole9** [comment]
I have pushed [url version 2.0.0](https://hex.pm/packages/url/2.0.0) with the following changelog entry:

### Breaking Change

* `URL.new/1` now always returns a tuple of the form `{:ok, t:URL.t/0}` or `{:error, {module(), String.t()}}`. The previous versions embedded error tuples in the return structure making is too complex to determine if there was a parsing error on the path data.  This approach also makes it more straight forward to implement tests that return errors.

### Deprecations

* Hard deprecates `URL.parse/1`

### Bug Fixes

* Remove warnings for unused variables when neither `ex_phone_number` or `ex_cldr` are configured (these are both optional dependencies). Thanks to @shahryarjb for the report. Closes #5.

**Comment by shahryarjb** [comment]
I am sorry to send another message sir, could you release in Github for version 2.0.0 please? 
@kipcole9 Thank you in advance

**Comment by kipcole9** [comment]
Done!
